### ISSUE TITLE
Preparing for release

### ISSUE THREAD

**Issue by spannercode** [cardanoapi/autonomous-agents#162]
## ToDo

- [x] Update DRep directory to include the metadata information; Refer GovTool. Add a link to GovTool DRep details page.
- [x] Update Governance actions to include the metadata information; Refer GovTool. Add a link to GovTool governance action details page on the governance action card
- [x] Fix scrolling by limiting to the list container instead of the full page
- [x] Show network name on the left sidebar

## Demo scenario
- Creating an agent
- Registering as DRep and showing the DRep on DRep directory.
- Using a pre-registered DRep with some voting power, vote on an existing proposal
- Show the updated votes on the proposal

**Comment by mesudip** [comment]
The issues mentioned in this tickets are fixed.
