### ISSUE TITLE
Agent Handler Service

### ISSUE THREAD

**Issue by mesudip** [cardanoapi/autonomous-agents#28]
Separate out  agent-manager service and support sending cardano-block events to the agents.

### Todo:
- [x] Setup Agent Hander service project as a sub-directory in the project.
- [x] Support subscribing events from cardano-node.
- [x] Send block mint events to cardano-agents.
