### ISSUE TITLE
Agent Key generation

### ISSUE THREAD

**Issue by mesudip** [cardanoapi/autonomous-agents#29]
Support generating seed phrases on agent  

### Expectation
When agent is created, A wallet should also be generated for the agent.

### ToDo
- [x] Look into seed-phrase generation with libcardano or bip39 deterministic keys and addresses
- [x] Update agent table to include the index field.
- [x] Create Api endpoint to fetch agent's wallet details and it's wallet address.
