### ISSUE TITLE
Milestone 1

### ISSUE THREAD

**Issue by spannercode** [cardanoapi/autonomous-agents#34]
### Tasks:
1. Defining agents, agent behaviors
2. Build a POC agent scheduling architecture
3.  Basic UI for adding agents, agent behaviors
4.  Basic UI for dashboard

### Measurement Criteria:

- [x] Figma Design of the dashboard is reviewed
- [x] Architecture document is ready.
- [x] PoC of agent scheduling infrastructure is created
- [x] Basic Dashboard UI
