### ISSUE TITLE
Deployment of milestone 1

### ISSUE THREAD

**Issue by spannercode** [cardanoapi/autonomous-agents#35]
Lets deploy the backend/frontend and the agents infrastructure covering the following:

- [x] Backend is deployed
- [x] frontend is deployed
- [x] N number of agents are started
- [x] N number of agents are shown online
- [x] N number of agents run some autonomous actions
- [x] Those actions are visible on the dashboard

Deployment URL: https://agents.cardanoapi.io

Additional Tasks:

- [x] Make sure the ReadMe are updated for each components (backend, frontend, agents)
