### ISSUE TITLE
Enhance Metrics and graphs

### ISSUE THREAD

**Issue by mesudip** [cardanoapi/autonomous-agents#80]
Fix issues and refactor ui/api for dashboard
### Todos:
- [x] Transactions graph (support time frame selection)
- [x] Fix x-axis labeling  (show timestamps on x axis instead of numbers)
- [x] Update backend-api to support time selection for transaction aggregation and update the frontend accordingly.
