### ISSUE TITLE
Final milestone

### ISSUE THREAD

**Issue by spannercode** [cardanoapi/autonomous-agents#98]
# Deliverables

- [x] A public GitHub repo with the code and documentation
- [ ] A YouTube video showing the dashboard and running a Voltaire voting scenario
- [ ] URL of the deployed Dashboard
- [ ] Closing report

# Output

- [ ] Addressing Community feedback
- [ ] Bug fixes of the major bugs reported
- [ ] Release of Dashboard URL
- [ ] Community promotion

# Acceptance Criteria

- [ ] Full source code is published to GitHub repo with sufficient documentation
- [ ] A YouTube video demonstrating the capability of the system is published and is public
- [ ] A URL of deployed environment
- [ ] Closing report
